# Generated by Django 3.2.7 on 2021-09-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fat', models.IntegerField()),
                ('dumb', models.IntegerField()),
                ('stupid', models.IntegerField()),
            ],
        ),
    ]
