# Generated by Django 3.2.7 on 2021-09-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_tgbot_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgbot',
            name='dumb',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tgbot',
            name='fat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tgbot',
            name='stupid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tgbot',
            name='user_id',
            field=models.TextField(unique=True),
        ),
    ]
