# Generated by Django 3.2.7 on 2021-09-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgbot',
            name='user_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='command',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
