# Generated by Django 3.2.7 on 2021-09-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210926_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgbot',
            name='dumb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tgbot',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tgbot',
            name='stupid',
            field=models.IntegerField(default=0),
        ),
    ]
