# Generated by Django 3.2.7 on 2021-09-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210926_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tgbot',
            old_name='user_name',
            new_name='username',
        ),
    ]
